  gmail_username: 'cool.snow.mail@gmail.com'
  gmail_password: '89272755555'
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
